// A reasonably complete list of countries (name + ISO2) and their phone
// calling codes, for the membership/profile forms' Country and Phone
// dropdowns. No external dependency needed for this.

export const COUNTRIES: { name: string; code: string; dial: string }[] = [
  { name: 'New Zealand', code: 'NZ', dial: '+64' },
  { name: 'Australia', code: 'AU', dial: '+61' },
  { name: 'China', code: 'CN', dial: '+86' },
  { name: 'United States', code: 'US', dial: '+1' },
  { name: 'Canada', code: 'CA', dial: '+1' },
  { name: 'United Kingdom', code: 'GB', dial: '+44' },
  { name: 'Ireland', code: 'IE', dial: '+353' },
  { name: 'France', code: 'FR', dial: '+33' },
  { name: 'Germany', code: 'DE', dial: '+49' },
  { name: 'Italy', code: 'IT', dial: '+39' },
  { name: 'Spain', code: 'ES', dial: '+34' },
  { name: 'Portugal', code: 'PT', dial: '+351' },
  { name: 'Netherlands', code: 'NL', dial: '+31' },
  { name: 'Belgium', code: 'BE', dial: '+32' },
  { name: 'Switzerland', code: 'CH', dial: '+41' },
  { name: 'Austria', code: 'AT', dial: '+43' },
  { name: 'Sweden', code: 'SE', dial: '+46' },
  { name: 'Norway', code: 'NO', dial: '+47' },
  { name: 'Denmark', code: 'DK', dial: '+45' },
  { name: 'Finland', code: 'FI', dial: '+358' },
  { name: 'Poland', code: 'PL', dial: '+48' },
  { name: 'Russia', code: 'RU', dial: '+7' },
  { name: 'Japan', code: 'JP', dial: '+81' },
  { name: 'South Korea', code: 'KR', dial: '+82' },
  { name: 'Hong Kong', code: 'HK', dial: '+852' },
  { name: 'Macau', code: 'MO', dial: '+853' },
  { name: 'Taiwan', code: 'TW', dial: '+886' },
  { name: 'Singapore', code: 'SG', dial: '+65' },
  { name: 'Malaysia', code: 'MY', dial: '+60' },
  { name: 'Thailand', code: 'TH', dial: '+66' },
  { name: 'Vietnam', code: 'VN', dial: '+84' },
  { name: 'Indonesia', code: 'ID', dial: '+62' },
  { name: 'Philippines', code: 'PH', dial: '+63' },
  { name: 'India', code: 'IN', dial: '+91' },
  { name: 'Pakistan', code: 'PK', dial: '+92' },
  { name: 'United Arab Emirates', code: 'AE', dial: '+971' },
  { name: 'Saudi Arabia', code: 'SA', dial: '+966' },
  { name: 'Israel', code: 'IL', dial: '+972' },
  { name: 'Turkey', code: 'TR', dial: '+90' },
  { name: 'South Africa', code: 'ZA', dial: '+27' },
  { name: 'Egypt', code: 'EG', dial: '+20' },
  { name: 'Nigeria', code: 'NG', dial: '+234' },
  { name: 'Kenya', code: 'KE', dial: '+254' },
  { name: 'Brazil', code: 'BR', dial: '+55' },
  { name: 'Mexico', code: 'MX', dial: '+52' },
  { name: 'Argentina', code: 'AR', dial: '+54' },
  { name: 'Chile', code: 'CL', dial: '+56' },
  { name: 'Colombia', code: 'CO', dial: '+57' },
  { name: 'Peru', code: 'PE', dial: '+51' },
  { name: 'Fiji', code: 'FJ', dial: '+679' },
  { name: 'Samoa', code: 'WS', dial: '+685' },
  { name: 'Tonga', code: 'TO', dial: '+676' },
  { name: 'Cook Islands', code: 'CK', dial: '+682' },
  { name: 'Papua New Guinea', code: 'PG', dial: '+675' },
  { name: 'Ukraine', code: 'UA', dial: '+380' },
  { name: 'Greece', code: 'GR', dial: '+30' },
  { name: 'Czech Republic', code: 'CZ', dial: '+420' },
  { name: 'Romania', code: 'RO', dial: '+40' },
  { name: 'Hungary', code: 'HU', dial: '+36' },
  { name: 'Iceland', code: 'IS', dial: '+354' }
].sort((a, b) => a.name.localeCompare(b.name));

export const DIAL_CODES = Array.from(new Set(COUNTRIES.map((c) => c.dial))).sort((a, b) => {
  return parseInt(a.replace('+', ''), 10) - parseInt(b.replace('+', ''), 10);
});
